const fs = require("fs");
const p = "C:/ai art/ai.js";
let t = fs.readFileSync(p, "utf8");
t = t.replace('function createWork(req, options) {', 'async function createWork(req, options) {');
t = t.replace('    const { codeRecord, prompt, type, duration, sourceWorkId = null } = options;', '    const { codeRecord, prompt, type, duration, sourceWorkId = null, originalPrompt = prompt, enhancedPrompt = prompt, controls = {} } = options;');
t = t.replace('    const intelligence = buildPromptIntelligence(prompt, type);', '    const normalizedControls = normalizeGeminiOptions(controls);\n    const intelligence = buildPromptIntelligence(originalPrompt, type);\n    intelligence.enhancedPrompt = enhancedPrompt || intelligence.enhancedPrompt;');
t = t.replace('        prompt,\n        originalPrompt: prompt,\n        enhancedPrompt: intelligence.enhancedPrompt,', '        prompt: enhancedPrompt,\n        originalPrompt,\n        enhancedPrompt: intelligence.enhancedPrompt,\n        title: buildWorkTitle(originalPrompt, type),');
t = t.replace('        qualityLevel: intelligence.qualityLevel,\n        styleSuggestions: intelligence.suggestedStyles,\n        processingPriority: codeRecord.processingPriority || "normal"', '        qualityLevel: intelligence.qualityLevel,\n        styleSuggestions: intelligence.suggestedStyles,\n        timeOfDay: normalizedControls.timeOfDay,\n        timeOfDayLabel: ({ auto: " ·ﬁ«∆Ì", day: "‰Â«—", night: "·Ì·" })[normalizedControls.timeOfDay],\n        visualStyle: normalizedControls.visualStyle,\n        styleLabel: ({ realistic: "Ê«ﬁ⁄Ì", cinematic: "”Ì‰„«∆Ì", commercial: "≈⁄·«‰Ì", anime: "√‰„Ì" })[normalizedControls.visualStyle],\n        cameraAnglePreset: normalizedControls.cameraAnglePreset,\n        cameraAngleLabel: ({ close: "ﬁ—Ì»…", medium: "„ Ê”ÿ…", wide: "Ê«”⁄…" })[normalizedControls.cameraAnglePreset],\n        outputQuality: normalizedControls.outputQuality,\n        qualityLabel: ({ normal: "⁄«œÌ…", high: "⁄«·Ì…", ultra: "›«∆ﬁ…" })[normalizedControls.outputQuality],\n        processingPriority: codeRecord.processingPriority || "normal"');
fs.writeFileSync(p, t);
